name: uxarray-pip
channels:
  - conda-forge
  - ncar
dependencies:
  - python
  - matplotlib
  - numpy=1.22
  - jupyterlab>=3
  - xarray
  - ipywidgets
  - dask
  - netcdf4
  - line_profiler
  - intake-esm
  - ncar-jobqueue
  - memory_profiler
  - numba
  - scipy
  - pip
  - pip:
    - git+https://github.com/UXARRAY/uxarray@integrate_anissa
    